# 全体設定ファイル

データベース:
  url: "sqlite:///../data/keiba.db"

資金管理:
  月間予算: 100000
  一日上限: 10000
  一レース上限: 5000
  最大レース数_一日: 3
  配分_基本:
    wide: 0.5
    sanrenpuku: 0.4
    sanrentan: 0.1

モデル:
  アルゴリズム: "catboost"
  期待値閾値: 1.1  # 期待値がこの値を超えない場合は「見送り」
